receivers:
  otlp: 
    # ...

processors:
  batch: {}

exporters:
  otlp/tempo: 
    # ...
  debug: 
    #...

service:
  telemetry: 
    metrics:
      # ...
  pipelines:
    traces:
      receivers: [...]
      processors: [...]
      exporters: [...]
    metrics: 
      receivers: [...]
      processors: [...]
      exporters: [...]
