grafana:
  adminPassword: ""
alertmanagerConfig:
  smtp:   # fill with the smtp credentials of your own Brevo account
    host: ""
    from: ""   # must be the verified address of your Brevo account
    username: "<smtp-username-brevo>" 
    password: "<smtp-password-brevo>"
    to: ""