apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: taskflow-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: taskflow
      rules:
        - alert: ServiceDown
          # [...]