apiVersion: networking.k8s.io/v1
kind: # [...]
metadata:
  name: taskflow-ingress
  namespace: # [...]
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            # [...]
          - path: /
            # [...]